# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"stockDataRoot": "00_utils.ipynb",
         "requestUrl": "00_utils.ipynb",
         "downloadSecUrl": "00_utils.ipynb",
         "secUrlPref": "00_utils.ipynb",
         "pageUnavailableRE": "00_utils.ipynb",
         "openFp": "00_utils.ipynb",
         "pickSave": "00_utils.ipynb",
         "pickLoad": "00_utils.ipynb",
         "pickLoadIfPath": "00_utils.ipynb",
         "savePklToDir": "00_utils.ipynb",
         "loadPklFromDir": "00_utils.ipynb",
         "saveSplitPklToDir": "00_utils.ipynb",
         "loadSplitPklFromDir": "00_utils.ipynb"}

modules = ["utils.py"]

doc_url = "https://ikedim01.github.io/secscan/"

git_url = "https://github.com/ikedim01/secscan/tree/master/"

def custom_doc_links(name): return None
