# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"setStockDataRoot": "00_utils.ipynb",
         "stockDataRoot": "00_utils.ipynb",
         "requestUrl": "00_utils.ipynb",
         "downloadSecUrl": "00_utils.ipynb",
         "secIndexUrl": "00_utils.ipynb",
         "downloadSecSoup": "00_utils.ipynb",
         "getCombString": "00_utils.ipynb",
         "secUrlPref": "00_utils.ipynb",
         "pageUnavailableRE": "00_utils.ipynb",
         "spacesPat": "00_utils.ipynb",
         "openFp": "00_utils.ipynb",
         "pickSave": "00_utils.ipynb",
         "pickLoad": "00_utils.ipynb",
         "pickLoadIfPath": "00_utils.ipynb",
         "savePklToDir": "00_utils.ipynb",
         "loadPklFromDir": "00_utils.ipynb",
         "saveSplitPklToDir": "00_utils.ipynb",
         "loadSplitPklFromDir": "00_utils.ipynb",
         "toDateStr": "00_utils.ipynb",
         "toDate": "00_utils.ipynb",
         "dateStrsBetween": "00_utils.ipynb",
         "formatDateStr": "00_utils.ipynb",
         "dateStr8Pat": "00_utils.ipynb",
         "curEasternUSTime": "00_utils.ipynb",
         "easternUSTimeZone": "00_utils.ipynb",
         "secBrowse": "00_utils.ipynb",
         "printSamp": "00_utils.ipynb",
         "printErrInfoOrAccessNo": "00_utils.ipynb"}

modules = ["utils.py",
           "recentFeed.py"]

doc_url = "https://ikedim01.github.io/secscan/"

git_url = "https://github.com/ikedim01/secscan/tree/master/"

def custom_doc_links(name): return None
