# AUTOGENERATED! DO NOT EDIT! File to edit: 04_getCikFilings.ipynb (unless otherwise specified).

__all__ = ['getRecent']

# Cell

from secscan import utils

# Cell

def getRecent(cik) :
    cik = str(cik).lstrip('0')
    restFilingsUrl = f'/submissions/CIK{cik.zfill(10)}.json'
    filingsJson = utils.downloadSecUrl(restFilingsUrl, restData=True, toFormat='json')
    recentList = filingsJson['filings']['recent']
    accNos = recentList['accessionNumber']
    print(len(accNos),'filings for',filingsJson['name'])
    fDates = [fDate.replace('-','') for fDate in recentList['filingDate']]
    return [(formType,accNo,fDate)
            for formType,accNo,fDate in zip(recentList['form'],accNos,fDates)]