# AUTOGENERATED! DO NOT EDIT! File to edit: 04_getCikFilings.ipynb (unless otherwise specified).

__all__ = ['getCikFilings']

# Cell

import json

from secscan import utils

# Cell

def getCikFilings(cik) :
    restFilingsUrl = f'https://data.sec.gov/submissions/CIK{str(cik).zfill(10)}.json'
    secTickerJson = json.loads(utils.requestUrl(restFilingsUrl,returnText=True))
    return secTickerJson