# AUTOGENERATED! DO NOT EDIT! File to edit: 09_scrape6K.ipynb (unless otherwise specified).

__all__ = ['default6KDir', 'scraper6K']

# Cell

import collections
import itertools
import os
import re

from secscan import utils, dailyList, basicInfo, infoScraper

default6KDir = os.path.join(utils.stockDataRoot,'scraped6K')

# Cell

class scraper6K(infoScraper.scraperBase) :
    def __init__(self, infoDir=default6KDir, startD=None, endD=None, fSuff='m.pkl', **pickle_kwargs) :
        super().__init__(infoDir, '6-K', startD=startD, endD=endD, fSuff=fSuff, **pickle_kwargs)
#     def scrapeInfo(self, accNo, formType=None) :
#         return parse6K(accNo, formType), None