# AUTOGENERATED! DO NOT EDIT! File to edit: 03_tickerMap.ipynb (unless otherwise specified).

__all__ = ['getSecTickerDict', 'secTickerListUrl']

# Cell

import json

from secscan import utils

# Cell

secTickerListUrl = '/files/company_tickers_exchange.json'
def getSecTickerDict() :
    secTickerJson = json.loads(utils.downloadSecUrl(secTickerListUrl))
    tickerPos = secTickerJson['fields'].index('ticker')
    cikPos = secTickerJson['fields'].index('cik')
    res = {}
    for tup in secTickerJson['data'] :
        ticker, cik = tup[tickerPos], tup[cikPos]
        if ticker not in res or int(res[ticker]) < cik:
            res[ticker] = str(cik)
    return res