# AUTOGENERATED! DO NOT EDIT! File to edit: 03_tickerMap.ipynb (unless otherwise specified).

__all__ = ['getSecTickerDict', 'getCikToTickersMap', 'secTickerListUrl']

# Cell

import collections

from secscan import utils

# Cell

secTickerListUrl = '/files/company_tickers_exchange.json'

def getSecTickerDict(field1='ticker', field2='cik', singleValue=True) :
    """
    Return mappings among ticker, cik, name, and exchange based on a
    downloaded list from the SEC. Returns a dict: field1 -> field2 values.
    If singleValue is True returns just the last field2 value found
    for each field1 value. Otherwise returns a list of all the field2
    values found for each field1 value.
    """
    secTickerJson = utils.downloadSecUrl(secTickerListUrl, toFormat='json')
    fieldList, dataList = secTickerJson['fields'], secTickerJson['data']
    field1Pos, field2Pos = fieldList.index(field1), fieldList.index(field2)
    print('SEC ticker list length',len(dataList),
          'with',len(set(tup[field1Pos] for tup in dataList)),'unique values')
    res = {} if singleValue else collections.defaultdict(list)
    for tup in dataList :
        field1Val, field2Val = str(tup[field1Pos]), str(tup[field2Pos])
        if singleValue :
            res[field1Val] = field2Val
        else :
            res[field1Val].append(field2Val)
    return res

def getCikToTickersMap() :
    """
    Returns a dict: cik -> list of corresponding tickers
    """
    return getSecTickerDict('cik', 'ticker', singleValue=False)


## Old code using company_tickers.json:
# def getCikToTickersMap() :
#     """
#     Retrieves and parses an SEC-maintained list mapping tickers to CIKs.
#     Returns a defaultdict: cik -> list of corresponding tickers
#     """
#     tickersJSON = utils.downloadSecUrl('/files/company_tickers.json', toFormat='json')
#     cikToTickers = collections.defaultdict(list)
#     for v in tickersJSON.values() :
#         cikToTickers[str(v['cik_str'])].append(v['ticker'])
#     return cikToTickers