# AUTOGENERATED! DO NOT EDIT! File to edit: 00_utils.ipynb (unless otherwise specified).

__all__ = ['stockDataRoot', 'requestUrl', 'downloadSecUrl', 'secUrlPref']

# Cell
import os

stockDataRoot = os.path.expanduser(os.path.join('~','secData2'))

# Cell
import requests

def requestUrl(url, timeout=5.0, nTries=3, returnText=False, **kwargs) :
    "Downloads a URL using the requests package."
    for i in range(nTries) :
        try :
            r = requests.get(url,timeout=timeout,params=kwargs)
            r.raise_for_status()
            return r.text if returnText else r
        except Exception as e :
            print('Error','downloading',url,'-',e)
            if i >= nTries-1 :
                raise

secUrlPref = 'https://www.sec.gov'
def downloadSecUrl(secSubUrl) :
    """
    Downloads a url from the SEC site, checking for a temporary outage message.
    """
    urlContents = requestUrl(secUrlPref+secSubUrl).text
    if urlContents.find('page is temporarily unavailable') >= 0 :
        raise Exception('temporary SEC outage')
    return urlContents